### ISSUE TITLE
worlds default?

### ISSUE THREAD

**Issue by JOrlex** [poggit-orphanage/WorldProtect#8]
is there a way where i can set the default perms for a worlds, like sayy /worlds set default build false?

**Comment by Awzaw** [comment]
WorldProtect uses the absence of config keys (or a config file...) to indicate not locked/protected, so this would require some changes to the plugin, and would not then produce the expected behaviour - owners would have to flag all worlds as "open" (or 'protected', for staff) to allow building.

A command to (un)protect and (un)lock all worlds (or all non configured worlds?) might be simpler, and cause less confusion.

**Comment by supercrafter333** [comment]
**Closed due to inactivity.**
